
GET https://localhost:7224/api/pokemon

###

GET https://localhost:7224/api/pokemon/3

###

POST https://localhost:7224/api/pokemon/17
Content-Type: application/json

{
  "id": 17,
  "name": "Articuno",
  "type1":{
    "TypeName": "Ice" },
  "type2": {
    "TypeName": "Flying" }
}


###

DELETE https://localhost:7224/api/pokemon/0

###

GET https://localhost:7224/api/pokemon/type/8

###

GET https://localhost:7224/api/pokemon/pokemontype/2
