
GET https://localhost:7224/api/pokemon

###

GET https://localhost:7224/api/pokemon/31

###

POST https://localhost:7224/api/pokemon/1
Content-Type: application/json

{
  "name": "Charizard",
  "type1": {
    "typeName": "Fire"
  },
  "type2": {
    "typeName": "Flying"
  },
  "pokemonWeaknesses": [
    {
      "type": {
        "typeName": "Water"
      }
    },
    {
      "type": {
        "typeName": "Electric"
      }
    }
  ],
  "pokemonStrengths": [
    {
      "type": {
        "typeName": "Grass"
      }
    },
    {
      "type": {
        "typeName": "Bug"
      }
    }
  ]
}





###

DELETE https://localhost:7224/api/pokemon/34

###

PUT https://localhost:7224/api/pokemon/42
Content-Type: application/json

{
  "name": "Dragonite",
  "type1": {
    "typeName": "Dragon"
  },
  "type2": {
    "typeName": "Flying"
  },
  "pokemonWeaknesses": [
    {
      "type": {
        "typeName": "Fairy"
      }
    },
    {
      "type": {
        "typeName": "Dragon"
      }
    }
  ],
  "pokemonStrengths": [
    {
      "type": {
        "typeName": "Grass"
      }
    },
    {
      "type": {
        "typeName": "Fighting"
      }
    }
  ]
}

###

GET https://localhost:7224/api/pokemon/type/8

###

GET https://localhost:7224/api/pokemon/pokemontype/2
