
GET https://localhost:7224/api/pokemon

###

GET https://localhost:7224/api/pokemon/3

###

POST https://localhost:7224/api/pokemon/11
Content-Type: application/json

{
  "name": "Articuno",
  "type1": {
    "TypeName": "Ice"
  },
  "type2": {
    "TypeName": "Flying"
  },
  "weaknesses": [
    {
      "type": {
        "typeName": "Fire"
      }
    }
  ],
  "strengths": [
    {
      "type": {
        "typeName": "Grass"
      }
    }
  ]
}



###

DELETE https://localhost:7224/api/pokemon/17

###

GET https://localhost:7224/api/pokemon/type/8

###

GET https://localhost:7224/api/pokemon/pokemontype/2
